export interface Guide { id: string; title: string; kind: 'Kapitel' | 'Optionaler Bereich' | 'Start'; steps: readonly string[]; completion: string }
const guide = (id: string, title: string, steps: string[], completion: string, kind: Guide['kind'] = 'Kapitel'): Guide => ({ id, title, kind, steps, completion });
/** Authored instructions only: reading a guide never calls progression or warp code. */
export const GUIDES: readonly Guide[] = [
  guide('title', 'Titel', ['Auf den Starttext klicken oder die angebotene Starttaste drücken.', 'Das Schlachtutorial beginnt mit Valentus am Hang.'], 'Weiter: Schlachtutorial.', 'Start'),
  guide('battle', 'Valentus · Schlachtutorial', [
    'Mit WASD/Pfeilen zum markierten Platz am Hang gehen; auf dem Handy das Steuerkreuz benutzen. Danach erscheint das taktische Raster.',
    'Pro Zug gibt es eine Bewegung bis zu vier Feldern und eine Aktion, in beliebiger Reihenfolge. Ein blaues Feld anklicken oder mit Pfeilen auswählen und Enter bestätigen. Die ausgeführte Bewegung ist verbraucht; Esc/Rechtsklick schließt nur die Zauberauswahl.',
    'Q / Strahl wählen, auf eine Linie mit Gegnern zielen und per Klick/Enter bestätigen. Beide ersten Krieger besiegen. Der Strahl darf den Jungen nicht treffen. Nach einer Aktion kannst du noch bewegen, wenn deine Bewegung frei ist.',
    'Vor den Gegneraktionen die Blickrichtung mit Pfeilen oder einem Nachbarfeld wählen, dann Enter / Zug beenden drücken. Das gilt auch nach dem letzten besiegten Gegner. Die angezeigte Gegnerreihenfolge folgt ihrem Tempo; dies ist eine Zugphasen-Regel des Prototyps, kein vollständiges CT-System.',
    'Beim Axtkämpfer R / Druckwelle wählen und eine erreichbare Fläche mit dem Gegner bestätigen. Die Vorschau zeigt Rückstoß und Aufprallschaden; der Junge in der Fläche bleibt geschützt. Danach Blickrichtung und Zugende bestätigen.',
    'Beim Armbrustschützen entweder den Schützen treffen oder in die angezeigte Bolzenlinie zwischen Schütze und Junge gehen. Leertaste / Warten wählen, zum Schützen blicken und den Zug beenden. Warten schützt vorne, wenn noch keine Aktion ausgeführt wurde; seitliche und rückwärtige Treffer verursachen mehr Schaden.',
    'Die Gegneranimation abwarten. Bewegung und Aktion werden zu Beginn des nächsten Spielerzugs wieder frei. Valentus verliert echte LP; der Tutorialschutz hält ihn bei mindestens einem LP und verhindert eine Niederlage im Schlachtutorial.',
  ], 'Nach dem Armbrust-Beat flieht der Junge; die inszenierte Verwundung führt zu „Verwundung“.'),
  guide('break', 'Verwundung', ['Die Szene läuft automatisch; es gibt hier keinen Kampf und keine Heilaufgabe.', 'Während der Wundennahaufnahme E / Atmen oder die Wunde anklicken: ein optionaler Atemzug, keine Heilung.', 'Zum Überspringen Leertaste halten; außerhalb der Wundennahaufnahme funktioniert auch E / Weiter halten.'], 'Automatisch oder nach Überspringen weiter zur Flucht.'),
  guide('flight', 'Flucht · beide Wegabschnitte', ['Dem vorgegebenen Weg nach rechts/unten folgen: WASD/Pfeile oder einen Punkt auf dem Weg anklicken. Die Kamera folgt auf den zweiten Bildschirm.', 'Nach dem automatischen Stolpern an der Wurzel weiter bis zum Bach gehen. Am Ufer E / Springen drücken oder nahe Valentus klicken.', 'Am Abhang E oder den Bereich nahe Valentus gedrückt halten, bis der Balken voll ist (Hinaufziehen).', 'Am krummen Stamm erneut halten, bis Abstützen abgeschlossen ist. Dann bis zum glitschigen Stein weitergehen.', 'Lauschen und die Wunde untersuchen sind optionale Pausen. Q/R lässt nur schwaches Licht aufglimmen, nicht kämpfen. Esc halten überspringt die Flucht.'], 'Der Sturz am Ende führt zur Zuflucht; beide Fluchtbilder gehören zu derselben Szene.'),
  guide('refuge', 'Zuflucht', ['Die Eingangsszene abwarten oder E/Esc halten, bis sie übersprungen ist.', 'Wenn „Aufrichten“ angeboten wird, E oder Maus gedrückt halten, bis der Balken voll ist.', 'Mit einzelnen E-Eingaben / Klicks acht Schritte zur Wiege machen. Zwischen den Schritten die Atempause abwarten; währenddessen zählt keine Eingabe.', 'Die Nahaufnahme abwarten, dann E / Hand heben oder klicken.'], 'Nach Hand und Licht automatisch weiter zu Lia.'),
  guide('lia', 'Lia · Buch und Kyra', ['Die Einleitung abwarten, bis Kyras Gespräch automatisch beginnt. Mit einzelnen E-Eingaben / Klicks auf Weiter vollständig lesen; vorher lässt sich das Buch noch nicht schließen.', 'Nach dem Gespräch die letzte Seite schließen. In der freien Phase mit WASD/Pfeilen oder Klick laufen.', 'Optional Blatt und Blumen untersuchen und ein gefundenes Lesezeichen auswählen. Das ist keine Voraussetzung für den Heimweg.', 'Zum Wegmarker rechts unten gehen und dort interagieren.'], 'Nach dem Kapiteltitel beginnt der Heimweg im Hohlweg, nicht auf der offenen Wiesenkarte.'),
  guide('world:wiese', 'Wiese · Heimweg', ['Mit WASD/Pfeilen oder Klick laufen; nahe Objekte mit E untersuchen. Fundstücke werden beim Näherkommen gesammelt; I öffnet das Inventar.', 'Optional den alten Baum untersuchen und die Kornblume sammeln. Links liegt der Waldrand, rechts oben die Felder.', 'Für den direkten Heimweg den Hohlweg-Ausgang am unteren Rand nehmen.'], 'Weiter: Hohlweg → Hof. Entdeckungen und Blumen sind keine Pflicht.', 'Optionaler Bereich'),
  guide('world:felder', 'Felder · Heimweg', ['Optional den Apfelbaum mit E schütteln und die gefallenen Äpfel beim Näherkommen sammeln.', 'Bank, Weizen und Rüben sind Erkundungen, keine Kapitelbedingungen.', 'Dem Feldweg zum unteren Ausgang folgen; dieser führt direkt zum Hof. Links geht es zurück zur Wiese.'], 'Weiter: Hof → sofort zum Versteck. Fallobst ist nicht für den späteren Proviant erforderlich.', 'Optionaler Bereich'),
  guide('world:waldrand', 'Waldrand · Vogeljunges', ['Optional das Vogeljunges bei der Eiche aufsammeln, indem du nahe herangehst.', 'Mit dem Jungen im Inventar an der Eiche E drücken: ins Nest zurücksetzen. Die danach fallende Feder kann gesammelt werden.', 'Stamm/Reisig untersuchen oder nahe dem Stamm mit E über das Hindernis springen. Für den Heimweg den rechten Ausgang zur Wiese nehmen.'], 'Weiter: Wiese → Hohlweg → Hof. Vogelrettung und Holz-Entdeckung sind optional.', 'Optionaler Bereich'),
  guide('world:hohlweg', 'Hohlweg · nach Hause', ['Dem begehbaren Weg nach rechts/Osten folgen; Wände und Böschungen nicht quer durchlaufen.', 'Optional Erde/Böschung untersuchen und das Kupferstück nahe dem Weg aufsammeln.', 'Den rechten Ausgang zum Hof nehmen. Oben geht es zurück zur Wiese.'], 'Weiter: Hof. Kein Fundstück ist für die Heimkehr nötig.'),
  guide('world:hof', 'Hof · Heimkehr', ['Beim Betreten des Hofs beginnt sofort der Überfall. Eltern und Dunkelschatten sind bereits vor dem Haus.', 'Links am Weg in der Böschung verstecken (ungefähr 104,185): E drücken oder das Ziel anklicken.'], 'Heimkehr abgeschlossen → Überfall. Vor dem Verstecken ist nur der Weg zur Deckung begehbar.'),
  guide('raid-approach', 'Überfall · Versteck', ['Links am Weg zur Böschung gehen (ungefähr 104,185).', 'E / „In der Böschung verstecken“ auslösen oder das Ziel anklicken. Die Versteckanimation abwarten.'], 'Weiter im selben Kapitel: aus dem Versteck beobachten. Lia hat keine Kampf- oder Zauberaktionen.'),
  guide('raid-farm', 'Überfall · beobachten', ['Im Versteck bleiben und die Nahaufnahmen mit E / Weiter oder dem Weiter-Knopf einzeln fortsetzen. Während Animationen auf die erneute Freigabe warten.', 'Nach dem Abzug der Reiter wird der Hof wieder begehbar. Zu den Eltern vor dem Haus gehen (ungefähr 267,207) und interagieren.', 'Den Schwur mit den angebotenen Weiter-Eingaben fortsetzen.'], 'Weiter: Hof am Morgen / Reisevorbereitung. Der Überfall kann nicht durch einen Kampf verhindert werden.'),
  guide('farm-dawn', 'Hof am Morgen · Aufbruch', ['Optional die beiden Gräber aufsuchen; Nahaufnahmen mit Zurück schließen.', 'Die Haustür bei 273,182 benutzen, um die sechs Vorbereitungen im Haus zu erledigen.', 'Nach vollständigem Packen durch „Zum Hof“ hinausgehen: dabei wird die Tür geschlossen. Falls sie noch offen ist, an der Tür „Tür schließen“ benutzen.', 'Das Schweinegatter links oben bei 154,108 öffnen. Zum Aufbruch müssen alle sechs Packaufgaben, geschlossene Tür und freigelassene Schweine erfüllt sein.', 'Dem Feldweg rechts oben zum Ziel „Weg nach Osten“ bei 596,40 folgen und dort interagieren.'], 'Wenn alles vorbereitet ist, weiter zur Straße nach Osten. Erneutes Betreten des Hauses öffnet die Tür wieder.'),
  guide('farm-interior', 'Haus · Reiseausrüstung', ['Am Medizinschrank links oben „Heilzeug einpacken“ benutzen: Mutters Tinktur und Leinen für unterwegs.', 'Links bei der Kleidung „Reisefertig machen“ benutzen; gibt Schuhe/Mantel/Decke als Reisezeug. Die Packaufgaben sind in beliebiger Reihenfolge möglich.', 'Rechts oben Proviant einpacken und daneben den Wasserschlauch mitnehmen.', 'Rechts am Küchenschrank das Geheimfach öffnen: Dolch, 22 Kupfer und 7 Silber.', 'Die beiden Bücher in der Mitte einpacken. Alle sechs Aufgaben müssen erledigt sein; wiederholtes Benutzen gibt keine weiteren Gegenstände.', 'Durch die Tür unten „Zum Hof“ gehen, dann Schweine freilassen und aufbrechen.'], 'Weiter: Hof am Morgen. Vollständiges Packen schließt beim Verlassen die Haustür.'),
  guide('road-east', 'Reise · Straße nach Osten', ['Zuerst zum Bach links/mittig bei 243,235 gehen und „Trinken und Wasser auffüllen“ benutzen.', 'Erst danach ist der Wegweiser bei 435,184 verfügbar: ansehen, um Osten zu wählen.', 'Zum rechten Ziel bei 590,193 gehen und „Nach Osten weitergehen“ benutzen. Vor der Wegwahl ist es gesperrt. Die vorbeiziehenden Reisenden sind Atmosphäre, keine Gesprächsaufgabe.'], 'Weiter im selben Reise-Kapitel: erstes Nachtlager.'),
  guide('first-camp', 'Reise · Nachtlager', ['Links unten bei 233,260 den grünen Regenmantel ausbreiten.', 'Rechts unten bei 409,251 trockenes Laub und Zweige sammeln.', 'An der Feuerstelle bei 317,225 Holz reiben: E halten, bis der Balken voll ist. Alternativ die Feuerstelle anklicken; die Reibung wird dann ohne Halten beendet.', 'An derselben Feuerstelle Brot und Käse essen. Der Proviant ist ein Reisebündel und wird durch diese Mahlzeit nicht verbraucht.', 'Zurück zum Mantel: Füße ansehen, die Nahaufnahme mit Hinlegen schließen und dort erneut „Hinlegen und zudecken“ benutzen.', 'Nach dem Schlafen die Begegnung mit Weiter fortsetzen. Wenn „Leise zur Straße“ erscheint, das Ziel rechts unten bei 545,282 benutzen.'], 'Weiter: Begegnung mit Foltan und Azar im selben Nachtlager. Die Schritte sind der Reihe nach freigeschaltet.'),
  guide('strangers', 'Reise · Foltan, Azar und Crios', ['Falls du gerade erwachst: die einzelnen Weiter-Eingaben der Nahaufnahme lesen. Danach „Leise zur Straße“ rechts unten benutzen; die Gefangennahme ist geskriptet.', 'In der Gefangennahme-Nahaufnahme „Zuhören“ und dann Weiter benutzen, bis das gesamte Gespräch beendet und die Fesseln gelöst sind.', 'Die Gefährten-Nahaufnahme mit „Zum Stern“ schließen. Links zum Ziel bei 155,188 gehen und „Crios ansehen“ benutzen.', 'Danach sind die Lagerziele nur noch für Beobachtungen nutzbar. Der Straßen-Ausgang startet keinen weiteren Tag.'], 'Ende des Prototyps. Die angekündigte Weiterreise zum Lager am Morgen ist noch nicht spielbar.'),
];

export interface GuideContext { scene: string; map?: string; area?: string; campStep?: string; beat?: string }
export function currentGuide(context: GuideContext): Guide | undefined {
  if (context.scene === 'raid' && ['hidden', 'departure', 'parents', 'vow'].includes(context.beat ?? '')) return GUIDES.find(g => g.id === 'raid-farm');
  const encounter = context.scene === 'journey' && ['waking', 'slip', 'bound', 'star', 'complete'].includes(context.campStep ?? '');
  const id = context.scene === 'world' ? `world:${context.map ?? 'wiese'}` : encounter ? 'strangers' : context.area ?? context.scene;
  return GUIDES.find(g => g.id === id);
}
