import { test, expect } from '@playwright/test';

test('walkthrough follows context, allows read-only selection and scrolls on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?scene=world&map=waldrand');
  await page.waitForFunction(() => (window as any).game?.scene.isActive('world'));
  const snapshot = () => page.evaluate(() => JSON.stringify((window as any).game.registry.get('world')));
  const before = await snapshot();
  await page.getByRole('button', { name: 'Debug · Playtest' }).click();
  await expect(page.getByLabel('Walkthrough für')).not.toBeVisible();
  await page.getByText('Walkthrough · Spoiler', { exact: true }).click();
  await expect(page.getByLabel('Walkthrough für')).toHaveValue('world:waldrand');
  await page.getByLabel('Walkthrough für').selectOption('battle');
  await expect(page.locator('#debug-guide-content')).toContainText('Druckwelle');
  await page.getByLabel('Walkthrough für').selectOption('strangers');
  await expect(page.locator('#debug-guide-content')).toContainText('Ende des Prototyps');
  await page.getByRole('button', { name: 'Aktueller Bereich' }).click();
  await expect(page.getByLabel('Walkthrough für')).toHaveValue('world:waldrand');
  expect(await snapshot()).toBe(before);
  expect(await page.locator('#playtest-dialog').evaluate(el => { el.scrollTop = el.scrollHeight; return el.scrollTop > 0 && el.scrollWidth <= el.clientWidth; })).toBe(true);
  await page.getByRole('button', { name: 'Schließen · Esc' }).click();
  await page.getByRole('button', { name: 'Debug · Playtest' }).click();
  await page.getByLabel('Einstieg').selectOption('strangers');
  await page.getByRole('button', { name: 'Zum Einstieg' }).click();
  await page.waitForFunction(() => (window as any).game.scene.isActive('journey'));
  await page.getByRole('button', { name: 'Debug · Playtest' }).click();
  await page.getByText('Walkthrough · Spoiler', { exact: true }).click();
  await expect(page.getByLabel('Walkthrough für')).toHaveValue('strangers');
  expect(errors).toEqual([]);
});
