#!/usr/bin/env python3
"""Title illustration pipeline (UI area).

raw Codex output (any 16:9-ish size) -> game/public/assets/ui/title.png (1280x720)
plus game/src/ui/titleData.ts with twinkle-star positions detected in the sky (for the DOM title animation).

Usage: python3 scripts/art/ui_title.py <raw.png> [--sky-bottom 0.42]
"""
import base64, io, json, sys
from pathlib import Path
import numpy as np
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'game/public/assets/ui'
W, H = 1280, 720


def crop_16_9(img: Image.Image) -> Image.Image:
    w, h = img.size
    tw, th = w, round(w * 9 / 16)
    if th > h:
        th, tw = h, round(h * 16 / 9)
    x0, y0 = (w - tw) // 2, (h - th) // 2
    return img.crop((x0, y0, x0 + tw, y0 + th))


def detect_stars(img: Image.Image, sky_bottom: float, limit: int = 90):
    """Small bright points in the sky band, brightest first (local maxima clearly above the surroundings)."""
    a = np.asarray(img.convert('RGB')).astype(np.float32)
    lum = a @ np.array([0.299, 0.587, 0.114], dtype=np.float32)
    blur = np.asarray(Image.fromarray(lum.astype(np.uint8)).filter(ImageFilter.GaussianBlur(6))).astype(np.float32)
    contrast = lum - blur
    ys = int(H * sky_bottom)
    stars = []
    taken = np.zeros_like(lum, dtype=bool)
    order = np.argsort(-contrast[:ys].ravel())
    for idx in order:
        y, x = divmod(int(idx), W)
        if contrast[y, x] < 38 or len(stars) >= limit:
            break
        if taken[max(0, y - 9):y + 10, max(0, x - 9):x + 10].any():
            continue
        taken[y, x] = True
        r, g, b = a[y, x]
        stars.append({'x': x, 'y': y, 'b': round(float(min(1.0, contrast[y, x] / 140)), 2),
                      'c': '#%02x%02x%02x' % (int(r), int(g), int(b))})
    return stars


def main():
    raw = Path(sys.argv[1])
    sky_bottom = float(sys.argv[sys.argv.index('--sky-bottom') + 1]) if '--sky-bottom' in sys.argv else 0.42
    img = crop_16_9(Image.open(raw).convert('RGB')).resize((W, H), Image.LANCZOS)
    OUT.mkdir(parents=True, exist_ok=True)
    img.save(OUT / 'title.png', optimize=True)
    stars = detect_stars(img, sky_bottom)
    buf = io.BytesIO()
    img.resize((96, 54), Image.LANCZOS).save(buf, 'JPEG', quality=70)
    preview = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()
    rows = ',\n'.join(f"  [{s['x']}, {s['y']}, {s['b']}, '{s['c']}']" for s in stars)
    (ROOT / 'game/src/ui/titleData.ts').write_text(
        '// GENERATED by scripts/art/ui_title.py from the title illustration. Do not edit by hand.\n'
        '/** Twinkling stars detected in assets/ui/title.png (1280x720): [x, y, brightness 0..1, colour]. */\n'
        f'export const TITLE_STARS: [number, number, number, string][] = [\n{rows},\n];\n'
        '/** Tiny blurred preview of the painting, shown (scaled up, blurred) until the full image is decoded. */\n'
        f"export const TITLE_PREVIEW = '{preview}';\n")
    print(f'title.png {(OUT / "title.png").stat().st_size // 1024} KB, {len(stars)} stars')


if __name__ == '__main__':
    main()
