import { describe, expect, it } from 'vitest';
import { MAPS } from "../../content/maps/index";
import { type MapDef, type Pt } from "./mapTypes";
import { clearWalkingLine, findWalkingPath, isMapWalkable } from "./navigation";

describe('Weltwege', () => {
  it('erreicht jeden Kartenausgang vom Start ohne durch Blocker zu laufen', () => {
    for (const map of Object.values(MAPS)) {
      const canWalk = (x: number, y: number) => isMapWalkable(map, x, y);
      for (const exit of map.exits) {
        const [x, y, width, height] = exit.rect;
        const endpoints: Pt[] = [];
        for (let px = x; px <= x + width; px += 1) {
          for (let py = y; py <= y + height; py += 1) if (canWalk(px, py)) endpoints.push([px, py]);
        }
        const goal = endpoints[Math.floor(endpoints.length / 2)];
        expect(goal, `${map.id} → ${exit.to}: begehbarer Ausgang`).toBeDefined();
        const route = findWalkingPath(map.start, goal, canWalk);
        expect(route.length, `${map.id} → ${exit.to}: zusammenhängender Weg`).toBeGreaterThan(0);
        let last = map.start;
        for (const point of route) { expect(clearWalkingLine(last, point, canWalk)).toBe(true); last = point; }
      }
    }
  });

  it('setzt jede Rückkehr auf einen begehbaren Punkt außerhalb des Ausgangs', () => {
    for (const map of Object.values(MAPS)) {
      for (const exit of map.exits) {
        if (exit.scene) continue; // Scene transitions have a separate travel contract test.
        const target = MAPS[exit.to], entry = target.entries[map.id];
        expect(entry, `${map.id} → ${exit.to}: Ankunft`).toBeDefined();
        expect(isMapWalkable(target, ...entry.at), `${exit.to}: ${entry.at}`).toBe(true);
        const returnExit = target.exits.find(e => e.to === map.id)!;
        const [x, y, width, height] = returnExit.rect;
        expect(entry.at[0] >= x && entry.at[0] <= x + width && entry.at[1] >= y && entry.at[1] <= y + height).toBe(false);
      }
    }
  });

  it('umgeht eine Bank und lehnt einen vollständig versperrten Weg ab', () => {
    const map = MAPS.felder, canWalk = (x: number, y: number) => isMapWalkable(map, x, y);
    const from: Pt = [250, 218], goal: Pt = [350, 218];
    expect(clearWalkingLine(from, goal, canWalk)).toBe(false);
    const route = findWalkingPath(from, goal, canWalk);
    expect(route.length).toBeGreaterThan(1);
    expect(route.at(-1)).toEqual(goal);
    expect(findWalkingPath([20, 100], [100, 100], (x, y) => y > 90 && y < 110 && (x < 40 || x > 80))).toEqual([]);
  });

  it('erreicht den Kartenrand auch bei einem Klick knapp außerhalb der Fußbreite', () => {
    const map = MAPS.wiese;
    const route = findWalkingPath(map.start, [635, 118], (x, y) => isMapWalkable(map, x, y));
    expect(route.at(-1)![0]).toBeGreaterThanOrEqual(632);
    expect(route.at(-1)![1]).toBeGreaterThanOrEqual(100);
    expect(route.at(-1)![1]).toBeLessThanOrEqual(136);
  });
});

type Rect = [number, number, number, number];
type Target = { id: string; at: Pt; radius: number; rect?: Rect };
const inRect = ([px, py]: Pt, [x, y, width, height]: Rect) => px >= x && px <= x + width && py >= y && py <= y + height;

function origins(map: MapDef): [string, Pt][] {
  return [['Start', map.start], ...Object.entries(map.entries).map(([id, entry]): [string, Pt] => [`Ankunft ${id}`, entry.at])];
}

/** Every integer landing generated by quests.ts, including all random offsets. */
function drops(map: MapDef): Target[] {
  return map.props.flatMap(prop => {
    if (prop.action === 'returnChick') return [{ id: `${prop.id}:dank-feder`, at: [prop.at[0] + 18, prop.at[1] + 10] as Pt, radius: 10 }];
    if (prop.action !== 'shakeTree') return [];
    const result: Target[] = [];
    for (const offset of [-14, 16]) for (let jitter = -4; jitter <= 4; jitter++) for (let dy = 6; dy <= 14; dy++) {
      result.push({ id: `${prop.id}:apfel:${offset}:${jitter}:${dy}`, at: [prop.at[0] + offset + jitter, prop.at[1] + dy], radius: 10 });
    }
    // A pickup bobs up by 2px. A 10px approach remains inside the runtime
    // collection radius of 12px throughout the animation and in reduced motion.
    return result;
  });
}

function targets(map: MapDef): Target[] {
  return [
    ...map.props.map(prop => ({ id: `Objekt ${prop.id}`, at: prop.at, radius: prop.radius - 0.1 })),
    ...(map.pickups ?? []).map(pickup => ({ id: `Fund ${pickup.id}`, at: pickup.at, radius: 10 })),
    ...drops(map),
    ...map.exits.map(exit => ({ id: `Ausgang ${exit.to}`, at: [exit.rect[0] + exit.rect[2] / 2, exit.rect[1] + exit.rect[3] / 2] as Pt, radius: 0, rect: exit.rect })),
    ...(map.triggers ?? []).map(trigger => ({ id: `Geschichte ${trigger.id}`, at: [trigger.rect[0] + trigger.rect[2] / 2, trigger.rect[1] + trigger.rect[3] / 2] as Pt, radius: 0, rect: trigger.rect })),
    ...(map.jumps ?? []).flatMap((jump, index) => [
      { id: `Sprung ${index}:a`, at: jump.a, radius: jump.radius - 0.1 },
      { id: `Sprung ${index}:b`, at: jump.b, radius: jump.radius - 0.1 },
    ]),
    // These animals react to distance in Critter.update. Pigs are behind their
    // fence and are observed through the schweine prop, rather than touched.
    ...(map.critters ?? []).flatMap((critter, index) => {
      const radii = { butterfly: 30, bird: 44, hare: 64, chicken: 22, pig: 0 };
      const result: Target[] = critter.kind === 'pig' ? [] : [{ id: `Tier ${index}:${critter.kind}`, at: critter.at, radius: radii[critter.kind] - 0.1 }];
      if (critter.burrow) result.push({ id: `Hasenbau ${index}`, at: critter.burrow, radius: 65 });
      return result;
    }),
  ];
}

/** Avoid automatic exits and story triggers until the intended destination. */
function targetWalkable(map: MapDef, target: Target) {
  const forbidden = [...map.exits.map(exit => exit.rect), ...(map.triggers ?? []).map(trigger => trigger.rect)]
    .filter(rect => rect !== target.rect);
  return (x: number, y: number) => isMapWalkable(map, x, y) && !forbidden.some(rect => inRect([x, y], rect));
}

function approachPoints(target: Target, walkable: (x: number, y: number) => boolean): Pt[] {
  if (!target.rect && walkable(...target.at)) return [target.at];
  const points: Pt[] = [];
  const [x, y, width, height] = target.rect ?? [target.at[0] - target.radius, target.at[1] - target.radius, target.radius * 2, target.radius * 2];
  for (let px = Math.ceil(x); px <= x + width; px++) for (let py = Math.ceil(y); py <= y + height; py++) {
    if (walkable(px, py) && (target.rect || Math.hypot(px - target.at[0], py - target.at[1]) < target.radius)) points.push([px, py]);
  }
  return points.sort((a, b) => Math.hypot(a[0] - target.at[0], a[1] - target.at[1]) - Math.hypot(b[0] - target.at[0], b[1] - target.at[1]));
}

function reachableApproach(map: MapDef, origin: Pt, target: Target): { from: Pt; route: Pt[] } | undefined {
  const walkable = targetWalkable(map, target), points = approachPoints(target, walkable);
  // Jump arcs cross blockers. Only the departure approach and exact landing
  // need walking collision, as in WorldScene.nearJump/jump.
  const starts: Pt[] = [origin], visited = new Set<string>([origin.join(',')]);
  for (let cursor = 0; cursor < starts.length; cursor++) {
    const from = starts[cursor];
    for (const goal of points) {
      const route = findWalkingPath(from, goal, walkable, 0);
      if (route.length) return { from, route };
    }
    for (const [index, jump] of (map.jumps ?? []).entries()) for (const [departure, landing, side] of [[jump.a, jump.b, 'a'], [jump.b, jump.a, 'b']] as const) {
      const key = `${index}:${side}`;
      if (visited.has(key) || !walkable(...landing)) continue;
      const pad: Target = { id: key, at: departure, radius: jump.radius - 0.1 };
      if (approachPoints(pad, walkable).some(goal => findWalkingPath(from, goal, walkable, 0).length > 0)) {
        visited.add(key); starts.push(landing);
      }
    }
  }
  return undefined;
}

describe.each(Object.values(MAPS))('Alle Ziele auf $id', map => {
  it.each(origins(map))('erreicht jedes Ziel ab %s vor einer automatischen Geschichte oder einem Kartenwechsel', (_label, origin) => {
    expect(isMapWalkable(map, ...origin), `begehbarer Start ${origin}`).toBe(true);
    const allTargets = targets(map);
    expect(allTargets.length).toBeGreaterThan(0);
    for (const target of allTargets) {
      const reached = reachableApproach(map, origin, target);
      expect(reached, `${map.id}: ${origin} → ${target.id} ${target.at}`).toBeDefined();
      const { from, route } = reached!;
      expect(route.length).toBeGreaterThan(0);
      const walkable = targetWalkable(map, target);
      let last = from;
      for (const point of route) {
        expect(clearWalkingLine(last, point, walkable), `${target.id}: Wegabschnitt ${last} → ${point}`).toBe(true);
        last = point;
      }
      if (target.rect) expect(inRect(last, target.rect), target.id).toBe(true);
      else expect(Math.hypot(last[0] - target.at[0], last[1] - target.at[1]), target.id).toBeLessThan(target.radius);
    }
  // The field case enumerates every apple landing and every origin, including
  // paths around the bent side-road verge. Keep the larger budget scoped here.
  }, map.id === 'felder' ? 20000 : 5000);

  it('hat sichere Absprung- und Landepunkte auf beiden Seiten aller Sprünge', () => {
    for (const jump of map.jumps ?? []) for (const pad of [jump.a, jump.b]) {
      expect(isMapWalkable(map, ...pad), `${map.id}: Sprunglandung ${pad}`).toBe(true);
      expect(map.exits.some(exit => inRect(pad, exit.rect))).toBe(false);
      expect((map.triggers ?? []).some(trigger => inRect(pad, trigger.rect))).toBe(false);
    }
  });

  it('bietet den Schweinen hinter dem Gatter eine erreichbare Beobachtungsstelle', () => {
    if ((map.critters ?? []).some(critter => critter.kind === 'pig')) {
      expect(map.props.some(prop => prop.id === 'schweine')).toBe(true);
    }
    // The hare travels to its burrow with the same 65px approach allowance.
    for (const hare of (map.critters ?? []).filter(critter => critter.burrow)) {
      const canWalk = (x: number, y: number) => isMapWalkable(map, x, y);
      const route = findWalkingPath(hare.at, hare.burrow!, canWalk, 65);
      expect(route.length, `${map.id}: Hase erreicht seinen Bau`).toBeGreaterThan(0);
      const end = route.at(-1)!;
      expect(Math.hypot(end[0] - hare.burrow![0], end[1] - hare.burrow![1])).toBeLessThanOrEqual(65);
    }
  });

  it.each(origins(map))('führt Objektklicks ab %s tatsächlich in Interaktionsreichweite', (_label, origin) => {
    const canWalk = (x: number, y: number) => isMapWalkable(map, x, y);
    for (const prop of map.props) {
      const route = findWalkingPath(origin, prop.at, canWalk, prop.radius);
      expect(route.length, `${map.id}: Klick auf ${prop.id}`).toBeGreaterThan(0);
      const end = route.at(-1)!;
      // WorldScene.arrive allows +6px; E and the visible prompt use the strict
      // prop radius. The tested endpoint works with both controls.
      expect(Math.hypot(end[0] - prop.at[0], end[1] - prop.at[1]), prop.id).toBeLessThan(prop.radius);
      let last = origin;
      for (const point of route) {
        expect(clearWalkingLine(last, point, targetWalkable(map, { id: prop.id, at: prop.at, radius: prop.radius })), `${prop.id}: Geschichte unterbricht den Klickweg`).toBe(true);
        last = point;
      }
    }
  });
});

describe('Nachweis der Reichweitenprüfung', () => {
  it('erkennt einen kurzen Fußkontakt an einer Grabkante auch auf einem langen Klickweg', () => {
    const map: MapDef = {
      ...MAPS.hof,
      walk: [[[0, 0], [640, 0], [640, 360], [0, 360]]],
      block: [[[226, 231], [244, 231], [244, 240], [226, 240]]],
    };
    const canWalk = (x: number, y: number) => isMapWalkable(map, x, y);
    const from: Pt = [247.46880678689888, 255.39067232241575], goal: Pt = [165, 205];
    // 3px line samples accepted this corner cut. Per-frame movement stopped
    // before the pig gate, although the planned segment looked clear.
    expect(clearWalkingLine(from, goal, canWalk)).toBe(false);
    const route = findWalkingPath(from, goal, canWalk);
    expect(route.length).toBeGreaterThan(1);
    let last = from;
    for (const point of route) {
      expect(clearWalkingLine(last, point, canWalk)).toBe(true);
      last = point;
    }
    expect(last).toEqual(goal);
  });

  it('erkennt einen Fund hinter einem Blocker trotz begehbarer Karte und vorhandener Ausgänge', () => {
    const map: MapDef = {
      id: 'versperrt', name: 'Prüfkarte', bg: '', start: [40, 100], entries: {}, props: [], exits: [],
      walk: [[[0, 0], [640, 0], [640, 360], [0, 360]]],
      block: [[[80, 0], [640, 0], [640, 360], [80, 360]]],
    };
    expect(reachableApproach(map, map.start, { id: 'zu weit', at: [100, 100], radius: 12 })).toBeUndefined();
  });

  it('nutzt einen gültigen Sprung, wenn die beiden begehbaren Seiten getrennt sind', () => {
    const map: MapDef = {
      id: 'sprung', name: 'Prüfkarte', bg: '', start: [50, 100], entries: {}, props: [], exits: [],
      walk: [[[0, 0], [640, 0], [640, 360], [0, 360]]],
      block: [[[100, 0], [140, 0], [140, 360], [100, 360]]],
      jumps: [{ a: [85, 100], b: [155, 100], radius: 10, hint: '' }],
    };
    const target: Target = { id: 'andere Seite', at: [200, 100], radius: 12 };
    expect(reachableApproach({ ...map, jumps: [] }, map.start, target)).toBeUndefined();
    expect(reachableApproach(map, map.start, target)?.from).toEqual([155, 100]);
  });
});
